# These substitutions allow the end user to override certain values
substitutions:
  name: "4-channel-wifi-module"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  # name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: intail.4-channel-wifi-module
    version: "1.0"

esp8266:
  board: esp12e

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# Activate the web server # version: 1 or 2
web_server:
  port: 80
#  version: 1 # or 2

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://mrred2k/esphome_relais_4_channel/4channel-relay-esp8266.yaml@main

wifi:
  # Set up a wifi access point using the device name above
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:


##########################################################
# Most projects should not remove anything from above here
# and should just modify the name, project name/version 
# and git url for the dashboard_import
##########################################################


# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:

##_____________Hardware Configuration____________##

switch:
  - platform: gpio
    pin: GPIO16 # LED (D1) connected
    name: ${name} Relay1
    id: relay1
  - platform: gpio
    pin: GPIO14 # LED (D5) connected
    name: ${name} Relay2
    id: relay2
  - platform: gpio
    pin: GPIO12 # LED (D9) connected
    name: ${name} Relay3
    id: relay3
  - platform: gpio
    pin: GPIO13 # LED (D11) connected
    name: ${name} Relay4
    id: relay4
  - platform: gpio
    pin: GPIO05 # LED (D9) connected; active LOW
    name: ${name} Output_GPIO05
    inverted: TRUE 
  - platform: gpio
    pin: GPIO04 # no LED connected; active LOW
    name: ${name} Output_GPIO04
    inverted: TRUE    
#  - platform: gpio
#    pin: GPIO00 # no LED connected; active LOW; use with caution (boot fails if pulled low)
#    name: ${name} Output_GPIO00
#    inverted: TRUE  
  - platform: gpio
    pin: GPIO15 # no LED connected; active LOW
    name: ${name} Output_GPIO15
    inverted: TRUE  

sensor:
#ADC Input
  - platform: adc
    pin: GPIO17
    name: ${name} ADC_raw
    update_interval: 60s
# Uptime Sensor
  - platform: uptime
    name:  ${name} Uptime
# Wifi Signal Sensor
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 120s


binary_sensor:
#Presents the node status to Homeassistant
  - platform: status
    name: ${name} Status
    
light:
#LED as a homeasstant connection indicator and dual porpuse swith
  - platform: status_led
    name: ${name} Status Led
    pin: GPIO2

#Buttons for board production | Delete after first use 
button:
  - platform: restart
    name: ${name}_restart
  - platform: factory_reset
    name: ${name} Reset to Factory